name: C++ CI

on: [push, pull_request]

jobs:
  Build-Run-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Run Tests
        run: make test
      - name: Run Main
        run: make run
      - name: Clean
        run: make clean
