name: C++ CI

on: [push, pull_request]

jobs:
  Build-Run-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run Main
      run: ./Main
    - name: make Test
      run: make test
    - name: clean 
      run: make clean
