name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Run Main
      run: ./Main
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: make Test
      run: make test
